version: '3.8'

services:
  eureka:
    image: java-naming-server
    depends_on:
      - db
    ports:
      - "8761:8761"

  rabbitmq:
    image: rabbitmq:3-management
    depends_on:
      - db
    ports:
      - "5672:5672"
      - "15672:15672"

  db:
    image: postgres:latest
    user: postgres
    environment:
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  user-service:
    image: user-service:latest
    ports:
      - "8200:8200"
      
  prediction-service:
    image: prediction-service:latest
    ports:
      - "8300:8300"

volumes:
  pgdata: